# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"SingleFilePathSchema": "extract_genetic_data.ipynb",
         "CaseControlFilePathSchema": "extract_genetic_data.ipynb",
         "MissingAttributeError": "extract_genetic_data.ipynb",
         "requires": "extract_genetic_data.ipynb",
         "GenFileFormat": "extract_genetic_data.ipynb",
         "row_vectorize": "extract_genetic_data.ipynb",
         "triplicate_converter": "extract_genetic_data.ipynb",
         "FILE_FORMAT_ENUM": "extract_genetic_data.ipynb",
         "FILE_TYPE_ENUM": "extract_genetic_data.ipynb",
         "OVPDataset": "extract_genetic_data.ipynb",
         "say_hello": "extract_genetic_data.ipynb"}

modules = ["datasets/genetic_datasets.py"]

doc_url = "https://hoangthienan95.github.io/nbdev_tutorial/"

git_url = "https://github.com/hoangthienan95/nbdev_tutorial/tree/master/"

def custom_doc_links(name): return None
